/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 * vim: set ts=8 sts=2 et sw=2 tw=80:
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef jitsbx_JitSandbox_h
#define jitsbx_JitSandbox_h

#include "jitsbx/JitSandboxExecutableMemory.h"
#include "threading/ProtectedData.h"
#include "vm/JSContext.h"

namespace js {

namespace jitsbx {

#if defined(JITSBX_CFI_BUNDLE) || defined(JITSBX_CFI_BUNDLE_ALIGN_INSTR)
static constexpr uint32_t BundleAlignment = 32; 
static constexpr int32_t IndirectCodeTargetMask = (MaxCodeBytesPerProcess - 1) & ~(BundleAlignment - 1);

inline bool isSameBundle(size_t x, size_t y) { 
  return (x / BundleAlignment) == (y / BundleAlignment);    
}

inline int toNextBundle(size_t offset) {
      return BundleAlignment - offset % BundleAlignment;
}
#endif

class JitSandbox {
 private:
#ifdef JITSBX_CFI_STACK
  // Separate sandbox-stack used while running code generated by the JIT.
  WriteOnceData<uint8_t*> sandboxStack_{nullptr};

  // Pointer to the end of the sandbox-stack for over-recursed checks.
  WriteOnceData<uintptr_t> sandboxStackLimit_{0};

  // Initial value for the stack pointer into the sandbox-stack.
  // We use this to reset the sandbox-stack pointer when the last
  // JIT Activation returns.
  WriteOnceData<uint8_t*> sandboxStackBasePtr_{nullptr};

  // Memory location outside the sandbox heap region where the JIT saves
  // the sandbox-stack pointer before switching to the native-stack.
  WriteOnceData<uintptr_t> addressOfSavedSandboxStackPtr_{0};

  // Memory location outside the sandbox heap region where the JIT saves
  // the native-stack pointer before switching to the sandbox-stack.
  WriteOnceData<uintptr_t> addressOfSavedNativeStackPtr_{0};

  // native-stack limit from the JSContext.
  WriteOnceData<uintptr_t> nativeStackLimit_{0};

  // Base of the native-stack from the JSContext.
  // We expect that JIT code will never point to the native-stack below
  // this limit.
  WriteOnceData<uintptr_t> nativeStackBasePtr_{0};
#endif

 public:
  JitSandbox() = default;
  ~JitSandbox();

  [[nodiscard]] bool initialize(JSContext* cx);

#ifdef JITSBX_CFI_STACK
  uintptr_t addressOfSavedNativeStackPtr() const {
    return addressOfSavedNativeStackPtr_;
  }

  const uint8_t* savedNativeStackPtr() {
    return *(uint8_t**)addressOfSavedNativeStackPtr_.ref();
  }

  void setSavedNativeStackPtr(const uint8_t* ptr) {
    *(uint8_t const**)addressOfSavedNativeStackPtr_.ref() = ptr;
  }

  uintptr_t addressOfSavedSandboxStackPtr() const {
    return addressOfSavedSandboxStackPtr_;
  }

  const uint8_t* savedSandboxStackPtr() {
    return *(uint8_t**)addressOfSavedSandboxStackPtr_.ref();
  }

  void setSavedSandboxStackPtr(const uint8_t* ptr) {
    *(uint8_t const**)addressOfSavedSandboxStackPtr_.ref() = ptr;
  }

  const uintptr_t* addressOfSandboxStackLimit() const {
    return &sandboxStackLimit_.ref();
  }

  uintptr_t sandboxStackLimit() const { return sandboxStackLimit_; }

  uintptr_t sandboxStackBase() const { return (uintptr_t)sandboxStackBasePtr_.ref(); }

  uintptr_t nativeStackLimit() const {
    return nativeStackLimit_.ref();
  }

  uintptr_t nativeStackBase() const { return (uintptr_t)nativeStackBasePtr_.ref(); }
#endif
};

#ifdef JITSBX_CFI_STACK
class NativeStackJitFrameLayout {
 private:
  uint8_t* callerFramePtr_;
  uint8_t* returnAddress_;

 public:
  static inline size_t Size() { return sizeof(NativeStackJitFrameLayout); }

  static constexpr size_t offsetOfReturnAddress() {
    return offsetof(NativeStackJitFrameLayout, returnAddress_);
  }
  uint8_t* returnAddress() const { return returnAddress_; }
  void setReturnAddress(uint8_t* addr) { returnAddress_ = addr; }

  static constexpr size_t offsetOfCallerFramePtr() {
    return offsetof(NativeStackJitFrameLayout, callerFramePtr_);
  }
  uint8_t* callerFramePtr() const { return callerFramePtr_; }
};

class MOZ_RAII AutoCheckSandboxStackRecursionLimit {
  [[nodiscard]] MOZ_ALWAYS_INLINE bool checkLimitImpl(uintptr_t limit,
                                                      void* sp) const;

 public:
  explicit MOZ_ALWAYS_INLINE AutoCheckSandboxStackRecursionLimit(JSContext* cx) {}
  MOZ_ALWAYS_INLINE ~AutoCheckSandboxStackRecursionLimit() {}

  AutoCheckSandboxStackRecursionLimit(const AutoCheckSandboxStackRecursionLimit&) = delete;
  void operator=(const AutoCheckSandboxStackRecursionLimit&) = delete;

  [[nodiscard]] MOZ_ALWAYS_INLINE bool check(JSContext* cx) const;
  [[nodiscard]] MOZ_ALWAYS_INLINE bool checkDontReport(JSContext* cx) const;
  [[nodiscard]] MOZ_ALWAYS_INLINE bool checkWithExtra(JSContext* cx,
                                                      size_t extra) const;
  [[nodiscard]] MOZ_ALWAYS_INLINE bool checkWithStackPointerDontReport(
      JSContext* cx, void* sp) const;
};

MOZ_ALWAYS_INLINE bool AutoCheckSandboxStackRecursionLimit::checkLimitImpl(
    uintptr_t limit, void* sp) const {
#  if JS_STACK_GROWTH_DIRECTION > 0
  return MOZ_LIKELY((uintptr_t)sp < limit);
#  else
  return MOZ_LIKELY((uintptr_t)sp > limit);
#  endif
}

MOZ_ALWAYS_INLINE bool AutoCheckSandboxStackRecursionLimit::check(JSContext* cx) const {
  if (MOZ_UNLIKELY(!checkDontReport(cx))) {
    ReportOverRecursed(cx);
    return false;
  }
  return true;
}

MOZ_ALWAYS_INLINE bool AutoCheckSandboxStackRecursionLimit::checkDontReport(
    JSContext* cx) const {
  void* sp = (void*)cx->runtime()->jitSandbox()->savedSandboxStackPtr();
  return checkWithStackPointerDontReport(cx, sp);
}

MOZ_ALWAYS_INLINE bool AutoCheckSandboxStackRecursionLimit::checkWithExtra(
    JSContext* cx, size_t extra) const {
  char* sp = (char*)cx->runtime()->jitSandbox()->savedSandboxStackPtr();
#  if JS_STACK_GROWTH_DIRECTION > 0
  sp += extra;
#  else
  sp -= extra;
#  endif
  if (MOZ_UNLIKELY(!checkWithStackPointerDontReport(cx, sp))) {
    ReportOverRecursed(cx);
    return false;
  }
  return true;
}

MOZ_ALWAYS_INLINE bool
AutoCheckSandboxStackRecursionLimit::checkWithStackPointerDontReport(JSContext* cx,
                                                            void* sp) const {
  uintptr_t sandboxStackLimit =
      cx->runtime()->jitSandbox()->sandboxStackLimit();
  if (MOZ_LIKELY(checkLimitImpl(sandboxStackLimit, sp))) {
    return true;
  }
  return false;
}
#endif

}  // namespace jitsbx
}  // namespace js

#endif /* jitsbx_JitSandbox_h */
