/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 * vim: set ts=8 sts=2 et sw=2 tw=80:
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef jitsbx_JitSandbox_h
#define jitsbx_JitSandbox_h

#include "threading/ProtectedData.h"

namespace js {

namespace jitsbx {

class JitSandbox {
 private:
#ifdef JITSBX_CFI_STACK
  // Separate sandbox-stack used while running code generated by the JIT.
  WriteOnceData<uint8_t*> sandboxStack_{nullptr};

  // Pointer to the end of the sandbox-stack for over-recursed checks.
  WriteOnceData<uintptr_t> sandboxStackLimit_{0};

  // Initial value for the stack pointer into the sandbox-stack.
  // We use this to reset the sandbox-stack pointer when the last
  // JIT Activation returns.
  WriteOnceData<uint8_t*> sandboxStackBasePtr_{nullptr};

  // Memory location outside the sandbox heap region where the JIT saves
  // the sandbox-stack pointer before switching to the native-stack.
  WriteOnceData<uintptr_t> addressOfSavedSandboxStackPtr_{0};

  // Memory location outside the sandbox heap region where the JIT saves
  // the native-stack pointer before switching to the sandbox-stack.
  WriteOnceData<uintptr_t> addressOfSavedNativeStackPtr_{0};

  // native-stack limit from the JSContext.
  WriteOnceData<uintptr_t> nativeStackLimit_{0};

  // Base of the native-stack from the JSContext.
  // We expect that JIT code will never point to the native-stack below
  // this limit.
  WriteOnceData<uintptr_t> nativeStackBasePtr_{0};
#endif

 public:
  JitSandbox() = default;
  ~JitSandbox();

  [[nodiscard]] bool initialize(JSContext* cx);

#ifdef JITSBX_CFI_STACK
  uintptr_t addressOfSavedNativeStackPtr() const {
    return addressOfSavedNativeStackPtr_;
  }

  const uint8_t* savedNativeStackPtr() {
    return *(uint8_t**)addressOfSavedNativeStackPtr_.ref();
  }

  void setSavedNativeStackPtr(const uint8_t* ptr) {
    *(uint8_t const**)addressOfSavedNativeStackPtr_.ref() = ptr;
  }

  uintptr_t addressOfSavedSandboxStackPtr() const {
    return addressOfSavedSandboxStackPtr_;
  }

  const uint8_t* savedSandboxStackPtr() {
    return *(uint8_t**)addressOfSavedSandboxStackPtr_.ref();
  }

  void setSavedSandboxStackPtr(const uint8_t* ptr) {
    *(uint8_t const**)addressOfSavedSandboxStackPtr_.ref() = ptr;
  }

  const uintptr_t* addressOfSandboxStackLimit() const {
    return &sandboxStackLimit_.ref();
  }

  uintptr_t sandboxStackLimit() const { return sandboxStackLimit_; }

  uintptr_t sandboxStackBase() const { return (uintptr_t)sandboxStackBasePtr_.ref(); }

  uintptr_t nativeStackLimit() const {
    return nativeStackLimit_.ref();
  }

  uintptr_t nativeStackBase() const { return (uintptr_t)nativeStackBasePtr_.ref(); }
#endif
};

}  // namespace jitsbx
}  // namespace js

#endif /* jitsbx_JitSandbox_h */
